server:
  port: ${port:10086}
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      # eureka服务地址，如果是集群的话，需要指定其它集群eureka地址（配置运行环境 -Dport=10086 -DdefaultZone=http://127.0.0.1:10087/eureka）
      defaultZone: ${defaultZone:http://127.0.0.1:10086/eureka}
    # 不注册自己（单个eureka服务）
#    register-with-eureka: false
    # 不拉取服务（单个eureka服务）
#    fetch-registry: false
  server:
    # 服务失效剔除时间间隔，默认60秒（单位：ms）
    eviction-interval-timer-in-ms: 60000
    # 关闭自我保护机制（开发模式建议关闭）
    # 自我保护机制的工作机制是：如果在15分钟内超过85%的客户端节点都没有正常的心跳，那么Eureka就认为客户端与注册中心出现了网络故障，Eureka Server自动进入自我保护机制，此时会出现以下几种情况：
    # 1. Eureka Server不再从注册列表中移除因为长时间没收到心跳而应该过期的服务。
    # 2. Eureka Server仍然能够接受新服务的注册和查询请求，但是不会被同步到其它节点上，保证当前节点依然可用。
    # 3. 当网络稳定时，当前Eureka Server新的注册信息会被同步到其它节点中。
    enable-self-preservation: false