server:
  port: 10010
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        # 配置cors跨域
        cors-configurations:
          '[/**]':
            # *表示全部
#            allowedOrigins: *
            allowedOrigins:
              - "http://docs.spring.io"
            allowedMethods:
              - GET
      routes:
        # 路由id，可以任意
        - id: user-service-route
          # 代理的服务地址，lb表示从eureka中获取具体服务(基于ribbon负载均衡)
#          uri: http://127.0.0.1:9091
          uri: lb://user-service
          # 路由断言，可以匹配映射路径
          predicates:
            - Path=/api/user/**
          filters:
            # 添加请求路径的前缀
            # http://localhost:10010/2 -> http://localhost:9091/user/2
#            - PrefixPath=/user
            # 去除请求路径的前缀，1表示过滤1个路径，2表示过滤2个路径，以此类推
            # http://localhost:10010/api/user/2 -> http://localhost:9091/user/2
            - StripPrefix=1
            # 自定义局部过滤器（MyParam过滤器过滤请求参数name）
            - MyParam=name
      # 默认过滤器会对所有路由都生效
      default-filters:
        # 添加响应头 X-Response-Foo: Bar 可以配置多个
        - AddResponseHeader=X-Response-Foo, Bar
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
ribbon:
  ConnectTimeout: 1000 # 连接超时时长
  ReadTimeout: 2000 # 数据通信超时时长
  MaxAutoRetries: 0 # 当前服务器的重试次数
  MaxAutoRetriesNextServer: 0 # 重试多少次服务
  OkToRetryOnAllOperations: false # 是否对所有的请求方式都重试
