server:
  port: 12000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/wuruixuan/springcloud-config.git
  rabbitmq:
    host: 192.168.3.26
    port: 5672
    username: heima
    password: heima
    virtual-host: /itcast
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
management:
  endpoints:
    web:
      exposure:
        # 暴露触发消息总线的地址
        include: bus-refresh